import { initializeApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';
import { getAuth } from 'firebase/auth';
import { getStorage } from 'firebase/storage';
import firebaseConfigLocal from '../../firebase-applet-config.json';

// Helper to safely fetch env vars including Portuguese translations auto-generated by browser translation on Vercel
const getEnvVar = (key: string, translatedKey?: string): string | undefined => {
  const env = import.meta.env as Record<string, string | undefined>;
  if (env[key]) return env[key];
  if (translatedKey && env[translatedKey]) return env[translatedKey];
  return undefined;
};

// Use environment variables if provided (useful for custom Vercel environments), otherwise fall back to local JSON
const firebaseConfig = {
  apiKey: getEnvVar('VITE_FIREBASE_API_KEY') || firebaseConfigLocal.apiKey,
  authDomain: getEnvVar('VITE_FIREBASE_AUTH_DOMAIN') || firebaseConfigLocal.authDomain,
  projectId: getEnvVar('VITE_FIREBASE_PROJECT_ID', 'ID_DO_PROJETO_VITE_FIREBASE') || firebaseConfigLocal.projectId,
  storageBucket: getEnvVar('VITE_FIREBASE_STORAGE_BUCKET', 'BALDE_DE_ARMAZENAMENTO_VITE_FIREBASE_DE_ARMAZENAMENTO') || firebaseConfigLocal.storageBucket,
  messagingSenderId: getEnvVar('VITE_FIREBASE_MESSAGING_SENDER_ID') || firebaseConfigLocal.messagingSenderId,
  appId: getEnvVar('VITE_FIREBASE_APP_ID', 'ID_DO_APLICATIVO_VITE_FIREBASE') || firebaseConfigLocal.appId,
  firestoreDatabaseId: getEnvVar('VITE_FIREBASE_DATABASE_ID', 'ID_DO_BANCO_DE_DADOS_VITE_FIREBASE') || firebaseConfigLocal.firestoreDatabaseId
};

export const app = initializeApp(firebaseConfig);
export const db = getFirestore(app, firebaseConfig.firestoreDatabaseId);
export const auth = getAuth(app);
export const storage = getStorage(app);

export function sanitizeForFirestore<T>(val: T): T {
  if (val === undefined) return null as any;
  if (val === null) return null as any;
  if (Array.isArray(val)) {
    return val.map(sanitizeForFirestore) as any;
  }
  if (typeof val === 'object') {
    const res: any = {};
    for (const key in val) {
      if (Object.prototype.hasOwnProperty.call(val, key)) {
        const v = val[key];
        if (v !== undefined) {
          res[key] = sanitizeForFirestore(v);
        }
      }
    }
    return res;
  }
  return val;
}

export enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId?: string | null;
    email?: string | null;
    emailVerified?: boolean | null;
    isAnonymous?: boolean | null;
  }
}

export function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null) {
  const errInfo: FirestoreErrorInfo = {
    error: error instanceof Error ? error.message : String(error),
    authInfo: {
      userId: auth.currentUser?.uid,
      email: auth.currentUser?.email,
      emailVerified: auth.currentUser?.emailVerified,
      isAnonymous: auth.currentUser?.isAnonymous,
    },
    operationType,
    path
  };
  console.error('Firestore Error: ', JSON.stringify(errInfo));
  throw new Error(JSON.stringify(errInfo));
}
